
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app_test
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:8
    # ports:
    #   - "6379:6379"

  web:
    build: .
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app_test
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: >
      sh -c "bundle exec rails db:test:prepare && bundle exec rspec"
