services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app_development
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:8

  web:
    build: .
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      # DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379/1
  sidekiq:
    build: .
    command: bundle exec sidekiq
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
volumes:
  pgdata:
  bundle_cache:
